/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface AuditEvent {
    id: bigint;
    requestId?: bigint;
    stylistId?: bigint;
    kind: string;
    createdAt: bigint;
    detail: string;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface ClientRequest {
    id: bigint;
    service: string;
    status: string;
    assignedStylistId?: bigint;
    recommendedStylistId?: bigint;
    idempotencyKey: string;
    timing: string;
    backupStylistId?: bigint;
    clientName: string;
    explanation: string;
    createdAt: bigint;
    specialtyMatters: boolean;
    updatedAt: bigint;
    notes: string;
    requestedTime: string;
    revision: bigint;
}
export interface Backup {
    dashboard: Dashboard;
    exportedAt: bigint;
    version: bigint;
}
export interface StylistInput {
    name: string;
    acceptsNewClients: boolean;
    availabilityExpiresAt: bigint;
    availabilityNote: string;
    phone: string;
    services: Array<ServicePreference>;
    availabilityStatus: string;
}
export interface Dashboard {
    audit: Array<AuditEvent>;
    stylists: Array<Stylist>;
    requests: Array<ClientRequest>;
}
export interface Stylist {
    id: bigint;
    active: boolean;
    assignments: bigint;
    name: string;
    createdAt: bigint;
    acceptsNewClients: boolean;
    availabilityExpiresAt: bigint;
    updatedAt: bigint;
    eligibleOpportunities: bigint;
    noResponses: bigint;
    lastAssignedAt: bigint;
    availabilityNote: string;
    phone: string;
    declines: bigint;
    revision: bigint;
    services: Array<ServicePreference>;
    availabilityStatus: string;
}
export interface Stylist__1 {
    name: string;
    specialty: string;
    availability: string;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface RouteInput {
    service: string;
    idempotencyKey: string;
    timing: string;
    clientName: string;
    specialtyMatters: boolean;
    notes: string;
    requestedTime: string;
}
export interface RoutingResult {
    request: ClientRequest;
    backup?: Stylist;
    recommended?: Stylist;
}
export interface ServicePreference {
    name: string;
    level: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addStylist(stylist: Stylist__1): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignRequest(requestId: bigint, stylistId: bigint, expectedRevision: bigint, note: string): Promise<ClientRequest>;
    createStylist(input: StylistInput): Promise<Stylist>;
    exportBackup(): Promise<Backup>;
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboard(): Promise<Dashboard>;
    getStylists(): Promise<Array<Stylist__1>>;
    isCallerAdmin(): Promise<boolean>;
    routeClient(input: RouteInput): Promise<RoutingResult>;
    setRequestStatus(requestId: bigint, status: string, expectedRevision: bigint, reason: string): Promise<ClientRequest>;
    setStylistActive(id: bigint, active: boolean, expectedRevision: bigint): Promise<Stylist>;
    updateStylist(id: bigint, input: StylistInput, expectedRevision: bigint): Promise<Stylist>;
    useBackup(requestId: bigint, expectedRevision: bigint, reason: string): Promise<RoutingResult>;
}
import type { AuditEvent as _AuditEvent, Backup as _Backup, ClientRequest as _ClientRequest, Dashboard as _Dashboard, Error as _Error, Result as _Result, RoutingResult as _RoutingResult, Stylist as _Stylist, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addStylist(arg0: Stylist__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStylist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStylist(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignRequest(arg0: bigint, arg1: bigint, arg2: bigint, arg3: string): Promise<ClientRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRequest(arg0, arg1, arg2, arg3);
                return from_candid_ClientRequest_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRequest(arg0, arg1, arg2, arg3);
            return from_candid_ClientRequest_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async createStylist(arg0: StylistInput): Promise<Stylist> {
        if (this.processError) {
            try {
                const result = await this.actor.createStylist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStylist(arg0);
            return result;
        }
    }
    async exportBackup(): Promise<Backup> {
        if (this.processError) {
            try {
                const result = await this.actor.exportBackup();
                return from_candid_Backup_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportBackup();
            return from_candid_Backup_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboard(): Promise<Dashboard> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboard();
                return from_candid_Dashboard_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboard();
            return from_candid_Dashboard_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStylists(): Promise<Array<Stylist__1>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStylists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStylists();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async routeClient(arg0: RouteInput): Promise<RoutingResult> {
        if (this.processError) {
            try {
                const result = await this.actor.routeClient(arg0);
                return from_candid_RoutingResult_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.routeClient(arg0);
            return from_candid_RoutingResult_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async setRequestStatus(arg0: bigint, arg1: string, arg2: bigint, arg3: string): Promise<ClientRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.setRequestStatus(arg0, arg1, arg2, arg3);
                return from_candid_ClientRequest_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRequestStatus(arg0, arg1, arg2, arg3);
            return from_candid_ClientRequest_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async setStylistActive(arg0: bigint, arg1: boolean, arg2: bigint): Promise<Stylist> {
        if (this.processError) {
            try {
                const result = await this.actor.setStylistActive(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStylistActive(arg0, arg1, arg2);
            return result;
        }
    }
    async updateStylist(arg0: bigint, arg1: StylistInput, arg2: bigint): Promise<Stylist> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStylist(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStylist(arg0, arg1, arg2);
            return result;
        }
    }
    async useBackup(arg0: bigint, arg1: bigint, arg2: string): Promise<RoutingResult> {
        if (this.processError) {
            try {
                const result = await this.actor.useBackup(arg0, arg1, arg2);
                return from_candid_RoutingResult_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.useBackup(arg0, arg1, arg2);
            return from_candid_RoutingResult_n20(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AuditEvent_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditEvent): AuditEvent {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Backup_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Backup): Backup {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_ClientRequest_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClientRequest): ClientRequest {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Dashboard_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Dashboard): Dashboard {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_RoutingResult_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoutingResult): RoutingResult {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Stylist]): Stylist | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dashboard: _Dashboard;
    exportedAt: bigint;
    version: bigint;
}): {
    dashboard: Dashboard;
    exportedAt: bigint;
    version: bigint;
} {
    return {
        dashboard: from_candid_Dashboard_n12(_uploadFile, _downloadFile, value.dashboard),
        exportedAt: value.exportedAt,
        version: value.version
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    audit: Array<_AuditEvent>;
    stylists: Array<_Stylist>;
    requests: Array<_ClientRequest>;
}): {
    audit: Array<AuditEvent>;
    stylists: Array<Stylist>;
    requests: Array<ClientRequest>;
} {
    return {
        audit: from_candid_vec_n14(_uploadFile, _downloadFile, value.audit),
        stylists: value.stylists,
        requests: from_candid_vec_n17(_uploadFile, _downloadFile, value.requests)
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    requestId: [] | [bigint];
    stylistId: [] | [bigint];
    kind: string;
    createdAt: bigint;
    detail: string;
}): {
    id: bigint;
    requestId?: bigint;
    stylistId?: bigint;
    kind: string;
    createdAt: bigint;
    detail: string;
} {
    return {
        id: value.id,
        requestId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.requestId)),
        stylistId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.stylistId)),
        kind: value.kind,
        createdAt: value.createdAt,
        detail: value.detail
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    request: _ClientRequest;
    backup: [] | [_Stylist];
    recommended: [] | [_Stylist];
}): {
    request: ClientRequest;
    backup?: Stylist;
    recommended?: Stylist;
} {
    return {
        request: from_candid_ClientRequest_n7(_uploadFile, _downloadFile, value.request),
        backup: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.backup)),
        recommended: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.recommended))
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    service: string;
    status: string;
    assignedStylistId: [] | [bigint];
    recommendedStylistId: [] | [bigint];
    idempotencyKey: string;
    timing: string;
    backupStylistId: [] | [bigint];
    clientName: string;
    explanation: string;
    createdAt: bigint;
    specialtyMatters: boolean;
    updatedAt: bigint;
    notes: string;
    requestedTime: string;
    revision: bigint;
}): {
    id: bigint;
    service: string;
    status: string;
    assignedStylistId?: bigint;
    recommendedStylistId?: bigint;
    idempotencyKey: string;
    timing: string;
    backupStylistId?: bigint;
    clientName: string;
    explanation: string;
    createdAt: bigint;
    specialtyMatters: boolean;
    updatedAt: bigint;
    notes: string;
    requestedTime: string;
    revision: bigint;
} {
    return {
        id: value.id,
        service: value.service,
        status: value.status,
        assignedStylistId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.assignedStylistId)),
        recommendedStylistId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.recommendedStylistId)),
        idempotencyKey: value.idempotencyKey,
        timing: value.timing,
        backupStylistId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.backupStylistId)),
        clientName: value.clientName,
        explanation: value.explanation,
        createdAt: value.createdAt,
        specialtyMatters: value.specialtyMatters,
        updatedAt: value.updatedAt,
        notes: value.notes,
        requestedTime: value.requestedTime,
        revision: value.revision
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AuditEvent>): Array<AuditEvent> {
    return value.map((x)=>from_candid_AuditEvent_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClientRequest>): Array<ClientRequest> {
    return value.map((x)=>from_candid_ClientRequest_n7(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
